# !  NOT FOR PRODUCTIOn
#
# Docker-compose for running the backend locally and mounting audio volumes
services:
  backend:
    container_name: music-portfolio-backend
    build: .
    volumes:
      - ./data:/app/data
      - ../public/audio:/app/public/audio # Mount audio files for local dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
