# ! PRODUCTION
#
# dockerfile used wthin the production environment

# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json before running npm install
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy the rest of the application files
COPY . .

# Expose port (change if necessary)
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
