name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to main
  workflow_dispatch: # Allows manual deployment from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r dist/* .  # Adjust this if your build output folder is different
          echo "test" > test.txt
          git add .
          git commit -m "Deploy to gh-pages"
          git push --force origin gh-pages
          
